#!/usr/bin/env python
import libvirt
import sys
import os
conn=libvirt.open("qemu:///system")
# This is where you add vms that will need to be monitored
sys.exit(0)
"""
dom = conn.lookupByName("ns2")
infos = dom.info()
if infos[0] == 1:
                print "Domain"
                sys.exit(0)
"""

"""
vms = ['qa2-srv', 'ns2']
# loope through vms and return 1 if up 5 if down
for vm in vms:
        dom = conn.lookupByName(vm)
        infos = dom.info()
        if infos[0] != 1:
                print "Domain %s is down" % (vm)
